// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/metrics/metrics.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// CreateRuleCounterInc mocks base method.
func (m *MockMetrics) CreateRuleCounterInc() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateRuleCounterInc")
}

// CreateRuleCounterInc indicates an expected call of CreateRuleCounterInc.
func (mr *MockMetricsMockRecorder) CreateRuleCounterInc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRuleCounterInc", reflect.TypeOf((*MockMetrics)(nil).CreateRuleCounterInc))
}

// RemoveRuleCounterInc mocks base method.
func (m *MockMetrics) RemoveRuleCounterInc() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveRuleCounterInc")
}

// RemoveRuleCounterInc indicates an expected call of RemoveRuleCounterInc.
func (mr *MockMetricsMockRecorder) RemoveRuleCounterInc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRuleCounterInc", reflect.TypeOf((*MockMetrics)(nil).RemoveRuleCounterInc))
}

// UpdateRuleCounterInc mocks base method.
func (m *MockMetrics) UpdateRuleCounterInc() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateRuleCounterInc")
}

// UpdateRuleCounterInc indicates an expected call of UpdateRuleCounterInc.
func (mr *MockMetricsMockRecorder) UpdateRuleCounterInc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRuleCounterInc", reflect.TypeOf((*MockMetrics)(nil).UpdateRuleCounterInc))
}
