version: "3.8"

services:
  app:
    build: .
    environment:
      CONFIG_DIR: docker
    restart: always
    ports:
      - "8000:8000"
    depends_on:
        - db
        - kafka
    command: make run
    networks:
        - ozonva

  db:
    image: postgres:13
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: "iloveozon"
      POSTGRES_USER: "ova"
      POSTGRES_DB: "ova"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
        ozonva:
            aliases:
              - pg-ova.lan

  zookeeper:
   image: "bitnami/zookeeper:latest"
   ports:
     - "2181:2181"
   environment:
     - ALLOW_ANONYMOUS_LOGIN=yes
   networks:
     - ozonva

  kafka:
   image: "bitnami/kafka:latest"
   ports:
     - "9092:9092"
   environment:
     - KAFKA_BROKER_ID=1
     - KAFKA_LISTENERS=PLAINTEXT://:9092
     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
     - ALLOW_PLAINTEXT_LISTENER=yes
   depends_on:
     - zookeeper
   networks:
     - ozonva

  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - "./tmp/prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - ozonva

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    networks:
      - ozonva

networks:
  ozonva:
      driver: bridge
